import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import QueryProvider from "@/features/providers/query-provider";

import { Toaster } from "@/components/ui/sonner"
import { JotaiProvider } from "@/features/providers/jotai-providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Room Etaaa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <JotaiProvider>
          <QueryProvider>
            {children}
            <Toaster />
          </QueryProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
